services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: sagaram-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - infra_pgdata:/var/lib/postgresql/data

volumes:
  infra_pgdata:

