services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: sagaram-postgres
    environment:
      POSTGRES_USER: sagaram
      POSTGRES_PASSWORD: sagaram123
      POSTGRES_DB: sagaram_lace
    ports:
      - "5432:5432"
    volumes:
      - infra_pgdata:/var/lib/postgresql/data

volumes:
  infra_pgdata:
